#!/bin/bash
# task 5.26

usage () {
cat << EOF
$0 options

Options:
    -d - execute 'date'
    -w - list working users
    -l - execute ls
EOF
}

[[ "$#" -eq 0 ]] && usage & exit 1

while getopts wdl arg
do
    case "$arg" in
    w) ;;
    d) ;;
    l) ;;
    ?) usage && exit 2;;
done


while getopts wdl arg
do
    case "$arg" in
    w) who | cut -d' ' -f 1 ;;
    d) date ;;
    l) ls ;;
done

